### ISSUE TITLE
I tried running your release but it complains: Library ntdll.dll not found !

### ISSUE THREAD

**Issue by DavidXanatos** [Coldzer0/Cmulator#1]
I tried running your release but it complains: "Library ntdll.dll not found !"
I have the hooks in the working directory as well as API.JS

**Comment by Coldzer0** [comment]
Hi @DavidXanatos 

in which **OS** you try to run **Cmulator** 

and please make sure you set paths on **config.json** 

cuz Cmulator need the windows dlls to be in the path you set so it loads it 

if you are on windows you can set it to 

for win 64
C:\Windows\SysWOW64 // this for 32bit files
C:\Windows\System32

for win 32 you can set win32 on config 
and for win64 you need to copy the dlls from another win 64 OS 


other OSs you need to copy the dlls from another win os

**Comment by Coldzer0** [comment]
i'll close this for now , if you have any problem in the future please don't hesitate to open new issue 
thanks
