### ISSUE TITLE
libraries not found

### ISSUE THREAD

**Issue by nicolasvillatte** [Coldzer0/Cmulator#2]
Cmulator is requiring some libraries that I am not able to find in either vc_redist or Windows SDK.

The error message is for instance: ""api-ms-win-core-job-l1-1-0.dll" not found !"

The DLL paths are correctly set as it does work on other libraries that are part of vc_redist.

api-ms-win-core-processthreads-l1-1-3.dll
api-ms-win-core-heap-l2-1-0.dll
api-ms-win-core-synch-l1-2-1.dll
api-ms-win-core-file-l1-2-2.dl
api-ms-win-core-job-l1-1-0.dll

Do you know where to find these and probably subsequents ones?

**Comment by Coldzer0** [comment]
Right now i'm implementing **ApiSetSchema API forwarder** to fix this issue, so all **api-ms-*** dlls won't be loaded anymore

I'll try my best to finish it ASAP.

**Comment by Coldzer0** [comment]
@nicolasvillatte 

Can you please check the latest release and test it.
https://github.com/Coldzer0/Cmulator/releases/tag/v0.2

Waiting your test
Thanks

**Comment by Coldzer0** [comment]
@nicolasvillatte 

Can you please check the latest release and test it.
https://github.com/Coldzer0/Cmulator/releases/tag/v0.2

Waiting your test
Thanks

**Comment by nicolasvillatte** [comment]
Thank you the problem is still present with other libraries.
The fix is apparently to populate the Apiset.json file matching the API with the proper DLL. Am I right?

**Comment by Coldzer0** [comment]
@nicolasvillatte

Yes, it based on parsing ".apiset" section from "apisetschema.dll".

Can you please upload the sample you're trying to run with Cmulator?

**Comment by Coldzer0** [comment]
You can join gitter community chat if you like, communication will be faster ^_^

https://gitter.im/x86_emulator/community

**Comment by nicolasvillatte** [comment]
Hi, I have been testing with AntiDbgx64.exe from your samples to start.
On Windows 10 x64 platform with Cmulator x64 Beta 0.2.
I'll join gitter later.

**Comment by Coldzer0** [comment]
Yep, you're right i tested on win10 x64 and it was a mess :D. 
Finally a working version :D

![image](https://user-images.githubusercontent.com/6647006/62532545-e7ef0900-b844-11e9-802f-9cbbb6279886.png)

![image](https://user-images.githubusercontent.com/6647006/62532772-795e7b00-b845-11e9-8790-5f9722f0a994.png)


I'll push & upload the latest version now

Thanks for your support and testing ^_^

**Comment by Coldzer0** [comment]
@nicolasvillatte 

Can you please test the latest release
https://github.com/Coldzer0/Cmulator/releases/tag/v0.2.1

Thanks.

**Comment by nicolasvillatte** [comment]
The last release fixed this issue.
Thank you for the quick fix.
