### ISSUE TITLE
export results to json format file ?

### ISSUE THREAD

**Issue by JohnWins** [Coldzer0/Cmulator#3]
hi,

Is it possiable to export results to json format file ?

for example: cpuid.exe

> CPUID at 0x40102E

> WriteFile('AuthenticAMD')

> ExitProcess(0x0)

> Cmulator Stop >> last Error : OK (UC_ERR_OK)

**Comment by Coldzer0** [comment]
You can control the printed output from the js code.

But yes i can add it as a feature, it will be a good feature for IOCs.

what do you think about this format
every api has its own predefined params.

```JSON
{
 "app":"cpuid.exe",
 "baseaddress":"0x400000",
 "more_pe_stuff":[],
 "APIS":[
  {"WriteFile":[{"handle":0},{"data":"AuthenticAMD"},{"length":13}]},
  {"ExitProcess":[{"ExitStatus":0}]}
],
"CPUIDS":["0x40102E"]
}
```

**Comment by JohnWins** [comment]
awesome! that's what I am looking to. 
nice to hear that it will support for more self defination;

**Comment by Coldzer0** [comment]
And soon i'll convert the full code to **C** so more people can contribute as there's not a lot of ppl interested in FreePascal.

I'll do it in a live stream videos, on youtube.

**Comment by JohnWins** [comment]
Well, that's amazing ! can't wait it any more .

**Comment by JohnWins** [comment]
hi, still wander to know how to control the js code and printed the output text into json format ?
currently, have little time to turn this project to C and to discuss it more .

**Comment by Coldzer0** [comment]
Hello @JohnWins 
I was preparing for the stream, but lately i was a bit busy.
I'll start today, hope i can continue without any disturb.

**Comment by Coldzer0** [comment]
Here's the new repo
https://github.com/Cmulator/Cmulator

**Comment by Coldzer0** [comment]
I'll start a fresh base for it with C language so ppl can contribute to it.

the new project will be here https://github.com/Cmulator/Cmulator
