### ISSUE TITLE
Can't find library in directory

### ISSUE THREAD

**Issue by HuErr** [Coldzer0/Cmulator#4]
[+] Fix IAT for : Qt5Core.dll                              --> Qt5Core.dll
"Qt5Core.dll" not found ! [4]

**Comment by Coldzer0** [comment]
@HuErr 

You need to put all needed dlls in the path you set into the config.json
The new update will have new option to set multi paths for dll search.

Plus Right now I don't support GUI Apps (will be supported later)

**Comment by HuErr** [comment]
Thanks !
