### ISSUE TITLE
Unable to find library ext-ms-win-dx-d3dkmt-dxcore.dll

### ISSUE THREAD

**Issue by EquilMinis** [Coldzer0/Cmulator#6]
Not sure if this is a trivial issue, but I'm getting this error when I attempt to run `Cemulator -f samples\AntiDbgx64.exe`.
[
![image](https://user-images.githubusercontent.com/63414434/82521759-c6100a00-9b6a-11ea-8030-4fbad8c18c7b.png)
](url)

Do I need to modify my `Apiset.js` file?

**Comment by Coldzer0** [comment]
There's a new version coming this month.

And yes you can update the apiset.json  

```
{name:"ext-ms-win-dx-d3dkmt-dxcore", count:1, red: ["dxcore.dll"]},
```

Actually I'll update the code to parse the `apiset` on the fly so it will depend on the system directory you specify on the config.json.

**Comment by EquilMinis** [comment]
Wow fast reply!
I tried adding `{name:"ext-ms-win-dx-d3dkmt-dxcore", count:1, red: ["dxcore.dll"]},` to the `WIN10_APIS` section of the apiset file, still getting the exact same `Library "C:\Windows\System32\ext-ms-win-dx-d3dkmt-dxcore.dll" not found ! [3]` issue, do I need to reload or something like that?

**Comment by Coldzer0** [comment]
This should fix it
```
{name:"ext-ms-win-dx-d3dkmt-dxcore-l1-1-0", count:1, red: ["dxcore.dll"]},
```


Can you please send your windows version and if you can test this version.
Thanks.


[Cmulator v0.3.0 Beta.zip](https://github.com/Coldzer0/Cmulator/files/4660660/Cmulator.v0.3.0.Beta.zip)

**Comment by EquilMinis** [comment]
First of all, thanks! It works :)

Windows version: Windows 10 Professional x64 build 1909

When I run your new release, I'm getting the error `ApiSetSchema JSON file not found - Check the config file !`, nothing else is printed?

**Comment by Coldzer0** [comment]
Oh sorry change the `"Apiset": "../Apiset.json"` in config.json `"Apiset": "./Apiset.json"`

**Comment by EquilMinis** [comment]
Ah yes that did it.

So it runs fine, but when I use it on AntiDbgx64, it seems like `IsDebuggerPresent` returns `1`?

Previous version
```
Initiating 13 Libraries ...

[>] Run AntiDbgx64.exe

IsDebuggerPresent = 0
MessageBoxA(0, 'Hi From Main Thread ..', ';)', 0x0)
ExitProcess(0x0)

28 Steps - Executed in 62 ms
Last Known Good (R/E)IP : 0x00000000703FCD84

Cmulator Stop >> last Error : OK (UC_ERR_OK)
```

Beta version
```
Initiating 21 Libraries ...

[>] Run AntiDbgx64.exe

IsDebuggerPresent = 1
MessageBoxA(0, 'Really -_-', ':P', 0x0)
ExitProcess(0x0)

29 Steps - Executed in 16 ms
Last Known Good (R/E)IP : 0x00000007003FCD84

Cmulator Stop >> last Error : OK (UC_ERR_OK)
```

**Comment by Coldzer0** [comment]
Open the `kernel32.js` line `78` and change the 1 to 0
And you can change what ever you want from the JS files.

Actually the next version will contain documentation so it will be easy to understand the code.

**Comment by EquilMinis** [comment]
Oh damn! That works perfectly... really nice how the hooks work.

Can't wait for the documentation :D

**Comment by Coldzer0** [comment]
So actually I'll not support this version of the project anymore I'll rewrite it with C language 
The project will be move to here https://github.com/Cmulator/Cmulator
